
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  " Ext.Msg": "../../src/window/MessageBox.js",
  "App": "../../../app",
  "Ext": "../../src",
  "Ext.rtl.EventObjectImpl": "../../src/rtl/EventObject.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "App.events.TestFileList": [],
  "App.events.LongTermGoalProgram_Activity": [],
  "App.components.fields.TableField": [],
  "App.events.WordCommonReport": [],
  "App.events.FinancialAndBusinessActivities": [],
  "App.components.fields.DateTime": [],
  "App.components.columns.Number": [],
  "App.events.AnalysisBAofDirectAndIndirectCost": [],
  "Ext.ux.DataView.DragSelector": [],
  "App.logic.ReportLauncher": [],
  "App.common.Ids": [],
  "App.events.FormElements": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "App.components.fields.TextArea": [],
  "App.events.Filter": [],
  "App.events.BalancingIFDB_RuleIndex": [],
  "App.events.SBP_Blank": [],
  "Ext.ux.PreviewPlugin": [],
  "App.clientactions.Eval": [],
  "App.ux.NumericField": [],
  "Ext.ux.ajax.SimXhr": [],
  "App.events.LongTermGoalProgram_ListSubProgram": [],
  "App.events.StateProgramGoalIndicatorValue": [],
  "Ext.ux.CellDragDrop": [],
  "App.events.AnalyticalCodeStateProgram": [],
  "App.events.PlanActivity_Activity": [],
  "App.components.fields.Date": [],
  "App.logic.mixins.ItemDenormalizer": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "App.components.FormulaCalculator": [],
  "App.events.TemplateExport": [],
  "App.view.Viewport": [],
  "App.logic.mixins.Columns": [],
  "App.view.ChangePassword": [],
  "Ext.ux.event.Recorder": [],
  "App.components.fields.FileLink": [],
  "App.events.ConsolidatedExpenditure_PPO": [],
  "App.events.PublicInstitutionEstimate_AloneAndBudgetInstitutionExpense": [],
  "App.view.Desktop": [],
  "App.common.Locale": [],
  "App.events.JustificationOfBudget": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "App.components.columns.Money": [],
  "App.logic.mixins.TablepartsDenormalizer": [],
  "Ext.ux.IFrame": [],
  "App.clientactions.YesSendQuestion": [],
  "App.patches.Connection": [],
  "Ext.ux.form.SearchField": [],
  "App.events.EntityField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "App.events.BalancingIFDB_Expense": [],
  "App.exceptions.Handler": [],
  "App.view.SysDimensions": [],
  "App.components.filters.StringFilter": [],
  "App.exceptions.UserFriendly": [],
  "App.events.ConsolidatedExpenditure": [],
  "App.components.mixins.LinkField": [],
  "App.events.FBA_ActivitiesDistribution": [],
  "App.events.TableReport": [],
  "App.logic.mixins.Cache": [],
  "App.components.ImportDialog": [],
  "App.events.BalancingIFDB": [],
  "Ext.ux.FieldReplicator": [],
  "App.components.fields.Hidden": [],
  "App.components.filters.LinkFilter": [],
  "App.logic.factory.Fields": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "App.util.Format": [],
  "App.components.mixins.ListMultiEdit": [],
  "App.events.NeedForTheProvisionOfActivitySbpWithinTheStateProgram": [],
  "Ext.ux.GMapPanel": [],
  "App.events.LimitBudgetAllocations": [],
  "App.logic.WindowManager": [],
  "App.events.PassportStateProgram": [],
  "App.events.BudgetExpenseStructure_Columns": [],
  "App.components.mixins.Versioning": [],
  "App.events.PublicInstitutionEstimate": [],
  "Ext.ux.GroupTabPanel": [],
  "App.components.menu.RangeMenu": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "App.events.PlanActivity_ActivityAUBU": [],
  "Ext.ux.layout.Center": [],
  "App.components.filters.NumericFilter": [],
  "App.components.Maximize": [],
  "App.components.columns.Text": [],
  "App.logic.SysDimensions": [],
  "Ext.ux.DataView.Animated": [],
  "App.events.FBA_Activity": [],
  "App.events.User": [],
  "App.components.mixins.ListExportImport": [],
  "App.view.Logs": [],
  "App.components.mixins.CommonField": [],
  "App.events.PublicInstitutionEstimate_ActivityAUBU": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "App.components.fields.Boolean": [],
  "App.components.columns.Date": [],
  "App.components.Search": [],
  "App.events.FileLinkList": [],
  "App.events.PlanActivity": [],
  "App.events.Entity": [],
  "App.events.LongTermGoalProgram": [],
  "Ext.ux.event.Player": [],
  "App.logic.ReportEntityItem": [],
  "App.exceptions.Control": [],
  "App.components.mixins.ListDocument": [],
  "App.components.filters.DateTimeFilter": [],
  "App.exceptions.Default": [],
  "Ext.ux.ToolbarDroppable": [],
  "App.events.PublicInstitutionEstimate_Expense": [],
  "App.events.ActivityOfSBP_Activity": [],
  "App.logic.mixins.Events": [],
  "App.events.PublicInstitutionEstimate_DistributionAdditionalParam": [],
  "Ext.ux.DataView.Draggable": [],
  "App.components.EntityGrid": [],
  "Ext.ux.TabCloseMenu": [],
  "App.events.AuthorityOfExpenseObligation": [],
  "App.events.BalancingIFDB_RuleFilterKBK": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "App.events.GoalIndicator": [],
  "App.components.Chart": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "App.components.columns.Boolean": [],
  "App.events.Budget": [],
  "App.controller.Login": [],
  "App.events.Form": [],
  "App.events.CommonList": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "App.logic.factory.Store": [],
  "App.logic.EntityItem": [],
  "App.events.PublicInstitutionEstimate_IndirectExpenses": [],
  "App.components.fields.TablePart": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "App.logic.ReportProfilesList": [],
  "App.events.ResourceMaintenanceOfTheStateProgram": [],
  "App.store.Navigation": [],
  "App.components.filters.DateFilter": [],
  "App.logic.FormManager": [],
  "App.components.MultiEditFormElement": [],
  "App.events.StateProgram": [],
  "App.events.testDependantTableFields": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "App.components.columns.Link": [],
  "App.view.Login": [],
  "App.components.columns.DateTime": [],
  "App.events.RegisterActivity_Activity": [],
  "App.common.Profile": [],
  "App.events.ForecastConsolidatedIndicators": [],
  "App.logic.StatusManager": [],
  "App.events.StateProgram_DepartmentGoalProgramAndKeyActivity": [],
  "App.components.fields.EnumComboBox": [],
  "App.events.SystemOfActivitySBP": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "App.patches.Summary": [],
  "App.logic.EntitiesList": [],
  "App.logic.factory.Buttons": [],
  "App.events.PlanActivity_KBKOfFinancialProvision": [],
  "App.components.ClosableButton": [],
  "App.direct.ControlingProvider": [],
  "App.events.SystemGoal": [],
  "App.events.Activity": [],
  "Ext.ux.ajax.SimManager": [],
  "App.logic.LogsManager": [],
  "App.events.ListProgram": [],
  "App.components.MultiEditDialog": [],
  "App.events.UserActivityReport": [],
  "Ext.ux.TabScrollerMenu": [],
  "App.events.CostGoals": [],
  "App.components.filters.BooleanFilter": [],
  "App.common.Guid": [],
  "App.events.Role": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "App.components.fields.GenericLink": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "App.events.EditionsComparision": [],
  "App.components.TaskBar": [],
  "App.components.fields.Text": [],
  "Ext.ux.InputTextMask": [],
  "App.logic.factory.Columns": [],
  "App.components.fields.Number": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "App.components.mixins.RegistryInfo": [],
  "App.events.Organization": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "App.events.FBA_IndirectCosts": [],
  "Ext.ux.GroupTabRenderer": [],
  "App.events.PublicInstitutionEstimate_DistributionActivity": [],
  "App.logic.factory.NavigationPanel": [],
  "App.components.TrayClock": [],
  "App.exceptions.System": [],
  "App.events.DirectionAndFundingOfDepartment": [],
  "App.components.EntityTreeGrid": [],
  "App.events.ActivityOfSBP_ActivityResourceMaintenance": [],
  "App.components.Navigation": [],
  "App.events.VcpOmStatePrg": [],
  "App.events.CommonTablePart": [],
  "App.events.BudgetExpenseStructure": [],
  "App.logic.factory.Field": [],
  "App.controller.Application": [],
  "App.components.mixins.ListStatusedReference": [],
  "App.events.PublicInstitutionEstimate_FounderAUBUExpense": [],
  "App.events.BalanceConfig_FilterKBK": [],
  "App.clientactions.Generic": [],
  "App.events.CommonItem": [],
  "App.components.mixins.FormField": [],
  "App.components.StartMenu": [],
  "App.events.RegisterActivity": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "App.events.ApprovalBalancingIFDB": [],
  "App.events.SummaryReportOfSelectedIndicators": [],
  "App.events.FBA_CostActivities": [],
  "App.events.SBP": [],
  "App.components.fields.Multilink": [],
  "App.events.ActivityOfSBP": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "App.logic.ModelManager": [],
  "App.components.FiltersFeature": [],
  "App.components.mixins.Operations": [],
  "App.events.Common": [],
  "App.events.RegistryGoal": [],
  "App.components.FileUploadDialog": [],
  "Ext.ux.event.Maker": [],
  "App.events.GoalTargetsOfProgramSbp": [],
  "App.components.fields.Money": [],
  "App.components.data.TreeStore": [],
  "App.events.XmlExport": [],
  "App.events.LimitBudgetAllocations_LimitAllocations": [],
  "App.logic.EntitiesManager": [],
  "App.events.StateProgram_ListSubProgram": [],
  "App.events.ConsolidatedRegisterOfServices": [],
  "App.logic.EnumsManager": [],
  "App.events.InterBudgetaryTransfers_RuleFilterKBK": [],
  "App.events.InterBudgetaryTransfers": [],
  "App.events.DocumentsOfSED": [],
  "App.components.fields.Link": [],
  "Ext.ux.DataTip": [],
  "App.logic.HttpRequest": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "App.components.ToolbarButton": [],
  "App.events.ActivityOfSBP_IndicatorQualityActivity": [],
  "App.events.Control": [],
  "App.events.PublicInstitutionEstimate_Activity": []
});
Ext.ClassManager.addNameAliasMappings({
  "App.events.TestFileList": [],
  "App.events.LongTermGoalProgram_Activity": [],
  "App.components.fields.TableField": [
    "widget.app_tablefield"
  ],
  "App.events.WordCommonReport": [],
  "App.events.FinancialAndBusinessActivities": [],
  "App.components.fields.DateTime": [
    "widget.app_datetimefield"
  ],
  "App.components.columns.Number": [],
  "App.events.AnalysisBAofDirectAndIndirectCost": [],
  "Ext.ux.DataView.DragSelector": [],
  "App.logic.ReportLauncher": [],
  "App.common.Ids": [],
  "App.events.FormElements": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "App.components.fields.TextArea": [
    "widget.app_textarea"
  ],
  "App.events.Filter": [],
  "App.events.BalancingIFDB_RuleIndex": [],
  "App.events.SBP_Blank": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "App.clientactions.Eval": [],
  "App.ux.NumericField": [],
  "Ext.ux.ajax.SimXhr": [],
  "App.events.LongTermGoalProgram_ListSubProgram": [],
  "App.events.StateProgramGoalIndicatorValue": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "App.events.AnalyticalCodeStateProgram": [],
  "App.events.PlanActivity_Activity": [],
  "App.components.fields.Date": [
    "widget.app_datefield"
  ],
  "App.logic.mixins.ItemDenormalizer": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "App.components.FormulaCalculator": [],
  "App.events.TemplateExport": [],
  "App.view.Viewport": [],
  "App.logic.mixins.Columns": [],
  "App.view.ChangePassword": [
    "widget.changeview"
  ],
  "Ext.ux.event.Recorder": [],
  "App.components.fields.FileLink": [],
  "App.events.ConsolidatedExpenditure_PPO": [],
  "App.events.PublicInstitutionEstimate_AloneAndBudgetInstitutionExpense": [],
  "App.view.Desktop": [],
  "App.common.Locale": [],
  "App.events.JustificationOfBudget": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "App.components.columns.Money": [],
  "App.logic.mixins.TablepartsDenormalizer": [],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "App.clientactions.YesSendQuestion": [],
  "App.patches.Connection": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "App.events.EntityField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "App.events.BalancingIFDB_Expense": [],
  "App.exceptions.Handler": [],
  "App.view.SysDimensions": [
    "widget.sysdimensions"
  ],
  "App.components.filters.StringFilter": [
    "gridfilter.extstring"
  ],
  "App.exceptions.UserFriendly": [],
  "App.events.ConsolidatedExpenditure": [],
  "App.components.mixins.LinkField": [],
  "App.events.FBA_ActivitiesDistribution": [],
  "App.events.TableReport": [],
  "App.logic.mixins.Cache": [],
  "App.components.ImportDialog": [],
  "App.events.BalancingIFDB": [],
  "Ext.ux.FieldReplicator": [],
  "App.components.fields.Hidden": [
    "widget.app_hiddenfield"
  ],
  "App.components.filters.LinkFilter": [
    "gridfilter.extlink"
  ],
  "App.logic.factory.Fields": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "App.util.Format": [],
  "App.components.mixins.ListMultiEdit": [],
  "App.events.NeedForTheProvisionOfActivitySbpWithinTheStateProgram": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "App.events.LimitBudgetAllocations": [],
  "App.logic.WindowManager": [],
  "App.events.PassportStateProgram": [],
  "App.events.BudgetExpenseStructure_Columns": [],
  "App.components.mixins.Versioning": [],
  "App.events.PublicInstitutionEstimate": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "App.components.menu.RangeMenu": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "App.events.PlanActivity_ActivityAUBU": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "App.components.filters.NumericFilter": [
    "gridfilter.extnumeric"
  ],
  "App.components.Maximize": [],
  "App.components.columns.Text": [],
  "App.logic.SysDimensions": [],
  "Ext.ux.DataView.Animated": [],
  "App.events.FBA_Activity": [],
  "App.events.User": [],
  "App.components.mixins.ListExportImport": [],
  "App.view.Logs": [],
  "App.components.mixins.CommonField": [],
  "App.events.PublicInstitutionEstimate_ActivityAUBU": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "App.components.fields.Boolean": [
    "widget.app_booleanfield"
  ],
  "App.components.columns.Date": [],
  "App.components.Search": [],
  "App.events.FileLinkList": [],
  "App.events.PlanActivity": [],
  "App.events.Entity": [],
  "App.events.LongTermGoalProgram": [],
  "Ext.ux.event.Player": [],
  "App.logic.ReportEntityItem": [],
  "App.exceptions.Control": [],
  "App.components.mixins.ListDocument": [],
  "App.components.filters.DateTimeFilter": [
    "gridfilter.extdatetime"
  ],
  "App.exceptions.Default": [],
  "Ext.ux.ToolbarDroppable": [],
  "App.events.PublicInstitutionEstimate_Expense": [],
  "App.events.ActivityOfSBP_Activity": [],
  "App.logic.mixins.Events": [],
  "App.events.PublicInstitutionEstimate_DistributionAdditionalParam": [],
  "Ext.ux.DataView.Draggable": [],
  "App.components.EntityGrid": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "App.events.AuthorityOfExpenseObligation": [],
  "App.events.BalancingIFDB_RuleFilterKBK": [],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "App.events.GoalIndicator": [],
  "App.components.Chart": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "App.components.columns.Boolean": [],
  "App.events.Budget": [],
  "App.controller.Login": [],
  "App.events.Form": [],
  "App.events.CommonList": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "App.logic.factory.Store": [],
  "App.logic.EntityItem": [],
  "App.events.PublicInstitutionEstimate_IndirectExpenses": [],
  "App.components.fields.TablePart": [
    "widget.app_tablepart"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "App.logic.ReportProfilesList": [],
  "App.events.ResourceMaintenanceOfTheStateProgram": [],
  "App.store.Navigation": [
    "store.navigation"
  ],
  "App.components.filters.DateFilter": [
    "gridfilter.extdate"
  ],
  "App.logic.FormManager": [],
  "App.components.MultiEditFormElement": [],
  "App.events.StateProgram": [],
  "App.events.testDependantTableFields": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "App.components.columns.Link": [],
  "App.view.Login": [
    "widget.loginview"
  ],
  "App.components.columns.DateTime": [],
  "App.events.RegisterActivity_Activity": [],
  "App.common.Profile": [],
  "App.events.ForecastConsolidatedIndicators": [],
  "App.logic.StatusManager": [],
  "App.events.StateProgram_DepartmentGoalProgramAndKeyActivity": [],
  "App.components.fields.EnumComboBox": [
    "widget.app_enumcombofield"
  ],
  "App.events.SystemOfActivitySBP": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "App.patches.Summary": [],
  "App.logic.EntitiesList": [],
  "App.logic.factory.Buttons": [],
  "App.events.PlanActivity_KBKOfFinancialProvision": [],
  "App.components.ClosableButton": [
    "widget.closebutton"
  ],
  "App.direct.ControlingProvider": [
    "direct.remotingprovider"
  ],
  "App.events.SystemGoal": [],
  "App.events.Activity": [],
  "Ext.ux.ajax.SimManager": [],
  "App.logic.LogsManager": [],
  "App.events.ListProgram": [],
  "App.components.MultiEditDialog": [],
  "App.events.UserActivityReport": [],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "App.events.CostGoals": [],
  "App.components.filters.BooleanFilter": [
    "gridfilter.extboolean"
  ],
  "App.common.Guid": [],
  "App.events.Role": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "App.components.fields.GenericLink": [
    "widget.app_genericlinkfield"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "App.events.EditionsComparision": [],
  "App.components.TaskBar": [
    "widget.taskbar"
  ],
  "App.components.fields.Text": [
    "widget.app_textfield"
  ],
  "Ext.ux.InputTextMask": [],
  "App.logic.factory.Columns": [],
  "App.components.fields.Number": [
    "widget.app_numberfield"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "App.components.mixins.RegistryInfo": [],
  "App.events.Organization": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "App.events.FBA_IndirectCosts": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "App.events.PublicInstitutionEstimate_DistributionActivity": [],
  "App.logic.factory.NavigationPanel": [],
  "App.components.TrayClock": [
    "widget.trayclock"
  ],
  "App.exceptions.System": [],
  "App.events.DirectionAndFundingOfDepartment": [],
  "App.components.EntityTreeGrid": [],
  "App.events.ActivityOfSBP_ActivityResourceMaintenance": [],
  "App.components.Navigation": [
    "widget.navigation"
  ],
  "App.events.VcpOmStatePrg": [],
  "App.events.CommonTablePart": [],
  "App.events.BudgetExpenseStructure": [],
  "App.logic.factory.Field": [],
  "App.controller.Application": [],
  "App.components.mixins.ListStatusedReference": [],
  "App.events.PublicInstitutionEstimate_FounderAUBUExpense": [],
  "App.events.BalanceConfig_FilterKBK": [],
  "App.clientactions.Generic": [],
  "App.events.CommonItem": [],
  "App.components.mixins.FormField": [],
  "App.components.StartMenu": [
    "widget.startmenu"
  ],
  "App.events.RegisterActivity": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "App.events.ApprovalBalancingIFDB": [],
  "App.events.SummaryReportOfSelectedIndicators": [],
  "App.events.FBA_CostActivities": [],
  "App.events.SBP": [],
  "App.components.fields.Multilink": [
    "widget.app_multilink"
  ],
  "App.events.ActivityOfSBP": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "App.logic.ModelManager": [],
  "App.components.FiltersFeature": [],
  "App.components.mixins.Operations": [],
  "App.events.Common": [],
  "App.events.RegistryGoal": [],
  "App.components.FileUploadDialog": [],
  "Ext.ux.event.Maker": [],
  "App.events.GoalTargetsOfProgramSbp": [],
  "App.components.fields.Money": [
    "widget.app_moneyfield"
  ],
  "App.components.data.TreeStore": [],
  "App.events.XmlExport": [],
  "App.events.LimitBudgetAllocations_LimitAllocations": [],
  "App.logic.EntitiesManager": [],
  "App.events.StateProgram_ListSubProgram": [],
  "App.events.ConsolidatedRegisterOfServices": [],
  "App.logic.EnumsManager": [],
  "App.events.InterBudgetaryTransfers_RuleFilterKBK": [],
  "App.events.InterBudgetaryTransfers": [],
  "App.events.DocumentsOfSED": [],
  "App.components.fields.Link": [
    "widget.app_linkfield"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "App.logic.HttpRequest": [],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "App.components.ToolbarButton": [
    "widget.toolbarbutton"
  ],
  "App.events.ActivityOfSBP_IndicatorQualityActivity": [],
  "App.events.Control": [],
  "App.events.PublicInstitutionEstimate_Activity": []
});
