
INSERT INTO [tp].[SBP_BlankHistory]
([idOwner]
,[DateCreate]
,[idBudget]
,[idBlankType]
,[idBlankValueType_ExpenseObligationType]
,[idBlankValueType_FinanceSource]
,[idBlankValueType_KFO]
,[idBlankValueType_KVSR]
,[idBlankValueType_RZPR]
,[idBlankValueType_KCSR]
,[idBlankValueType_KVR]
,[idBlankValueType_KOSGU]
,[idBlankValueType_DFK]
,[idBlankValueType_DKR]
,[idBlankValueType_DEK]
,[idBlankValueType_CodeSubsidy]
,[idBlankValueType_BranchCode]
)
SELECT [idOwner]
,getdate()
,[idBudget]
,[idBlankType]
,[idBlankValueType_ExpenseObligationType]
,[idBlankValueType_FinanceSource]
,[idBlankValueType_KFO]
,[idBlankValueType_KVSR]
,[idBlankValueType_RZPR]
,[idBlankValueType_KCSR]
,[idBlankValueType_KVR]
,[idBlankValueType_KOSGU]
,[idBlankValueType_DFK]
,[idBlankValueType_DKR]
,[idBlankValueType_DEK]
,[idBlankValueType_CodeSubsidy]
,[idBlankValueType_BranchCode]
FROM [tp].[SBP_Blank]


