IF EXISTS (SELECT name FROM sys.databases WHERE name = N'{0}') BEGIN ALTER DATABASE [{0}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [{0}]; END;
CREATE DATABASE [{0}];
ALTER DATABASE [{0}] MODIFY FILE ( NAME = N'{0}', FILEGROWTH = 5120KB );
ALTER DATABASE [{0}] MODIFY FILE ( NAME = N'{0}_log', FILEGROWTH = 5120KB );
ALTER DATABASE [{0}] SET CURSOR_CLOSE_ON_COMMIT ON;
ALTER DATABASE [{0}] SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE [{0}] SET READ_COMMITTED_SNAPSHOT ON;
ALTER DATABASE [{0}] SET QUOTED_IDENTIFIER ON;
ALTER DATABASE [{0}] SET TRUSTWORTHY ON;
ALTER DATABASE [{0}] SET ENABLE_BROKER;
ALTER AUTHORIZATION ON DATABASE::{0} TO sa
exec sp_configure 'show advanced options', 1;
RECONFIGURE;
exec sp_configure 'disallow results from triggers', 0;


RECONFIGURE;

